defaults: &defaults
  sendhub:
    api_key: '313095995b2ebb6f93e6ef4a3ea198d6338676d2'
    phone: '4047176779'
  phone_carriers:
    att: 
      name: 'AT&T'
      domain: 'txt.att.net'
    verizon: 
      name: 'Verizon'
      domain: 'vtext.com'  	
    tmobile: 
      name: 'T-Mobile'
      domain: 'tmomail.net'
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults